### ISSUE TITLE
Using this seems to mess up the percentage bar location

### ISSUE THREAD

**Issue by Fnige** [FireMario211/Golden-Best#1]
With only gb:
![image](https://github.com/FireMario211/Golden-Best/assets/35159947/57940ce0-a2cf-455f-a756-dc3f9898ca27)

With only gb when getting a new best:
![image](https://github.com/FireMario211/Golden-Best/assets/35159947/b528ed29-ab49-4b2f-b9ec-f9ebdc29a465)

And now the attempt after:
![image](https://github.com/FireMario211/Golden-Best/assets/35159947/d6f40056-806e-4cc4-956d-0ec45f3a46ca)

**Comment by FireMario211** [comment]
Fixed
