### ISSUE TITLE
1.0.2 causes level percentage to disappear when playing from a start position

### ISSUE THREAD

**Issue by Flyingturtle215** [FireMario211/Golden-Best#3]
Percentage disappears when playing from a start position. Only started happening after updating to 1.0.2, and doesn't happen in practice mode from 0.
![image](https://github.com/FireMario211/Golden-Best/assets/91761140/a79d19b3-d258-48a3-805e-4ee38f935b4b)

**Comment by FireMario211** [comment]
It was a silly mistake from me. It should be fixed in the new **v1.0.3** update.
